" Basic options
set number
set nobackup
set autochdir
set hlsearch
set fileencodings=utf-8,euc-kr,cp949
set encoding=utf-8
syntax on

" Indent, tab
set autoindent
set smartindent
inoremap # X#
set shiftwidth=4
set softtabstop=4
set expandtab
autocmd FileType markdown setlocal shiftwidth=2 softtabstop=2

" Save, quit
map <Space>q <ESC>:q<CR>
map <Space>w <ESC>:wa<CR>

" Navigation
map <S-RIGHT> <END>
imap <S-RIGHT> <END><ESC>
map <S-LEFT> <HOME>
imap <S-LEFT> <HOME>
map <S-DOWN> <C-d>
imap <S-DOWN> <ESC><C-d>
map <S-UP> <C-u>
imap <S-UP> <ESC><C-u>
nmap <C-RIGHT> <C-w>l
nmap <C-LEFT> <C-w>h
nmap <C-UP> <C-w>k
nmap <C-DOWN> <C-w>j

" Plugin
call plug#begin('~/.vim/plugged')
Plug 'preservim/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'neomake/neomake'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
Plug 'dkarter/bullets.vim'
Plug 'davidhalter/jedi-vim'
Plug 'ryanoasis/vim-devicons'
Plug 'tpope/vim-commentary'
call plug#end()


" Use 24-bit (true-color) mode.
" The code below is copied from
" onedark github page: https://github.com/joshdick/onedark.vim
if (empty($TMUX))
  if (has("nvim"))
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  if (has("termguicolors"))
    set termguicolors
  endif
endif

" Theme
set cursorline
colorscheme onedark
let g:airline_theme = 'onedark'
let g:airline_powerline_fonts = 1
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
set noshowmode

" Neomake syntax check
let g:neomake_python_enabled_makers = ['python']
try
    call neomake#configure#automake('w')
catch
endtry

" NERDTree
nmap <Space>f :NERDTreeToggle<CR>
let NERDTreeMapUpdirKeepOpen = "u"
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let NERDTreeDirArrowExpandable = ""
let NERDTreeDirArrowCollapsible = ""
let g:DevIconsEnableFoldersOpenClose = 1
let g:WebDevIconsNerdTreeBeforeGlyphPadding = " "
highlight! link NERDTreeFlags NERDTreeDir

" Buffer control
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'
nmap { :bprevious!<Enter>
nmap } :bnext!<Enter>
nmap <Space>db :bp <BAR> bd #<Enter>

" Run python script
map <Space>r :w !python %<CR>

" Gitgutter
autocmd BufWritePost * GitGutter

" JEDI-VIM
let g:jedi#show_call_signatures = 0
let g:jedi#completions_command = "<C-n>"
let g:jedi#popup_on_dot = 0
autocmd FileType python setlocal completeopt-=preview
